customhost = "order-form.cnbzgf9xxeai.us-east-2.rds.amazonaws.com"
customuser = "pnxrock101"
custompass = "Awsdb28650"
customdb = "orderform"
custombucket = "add-ordr-form"
customregion = "us-east-2"
